CREATE DATABASE IF NOT EXISTS LOCADORA;
USE LOCADORA;

CREATE TABLE IF NOT EXISTS FILMES(
id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
	ano int NOT NULL
);

SELECT * FROM FILMES