CREATE DATABASE IF NOT exists ESCOLA;
USE ESCOLA;

CREATE TABLE IF NOT EXISTS PROFESSORES (
id INT AUTO_INCREMENT PRIMARY KEY,
    nome_do_professor VARCHAR(100) NOT NULL,
	nome_da_materia VARCHAR(100) NOT NULL
);

SELECT * FROM PROFESSORES