CREATE DATABASE IF NOT EXISTS INSTITUICAO;
USE INSTITUICAO;

CREATE TABLE IF NOT EXISTS CURSOS(
id INT AUTO_INCREMENT PRIMARY KEY,
    nome_do_curso VARCHAR(100) NOT NULL,
	carga_horaria float  NOT NULL
);

SELECT * FROM CURSOS