CREATE DATABASE IF NOT EXISTS EMPRESA;
USE EMPRESA;

CREATE TABLE IF NOT EXISTS CLIENTES(
id INT AUTO_INCREMENT PRIMARY KEY,
    nome_do_cliente VARCHAR(100) NOT NULL,
	telefone_do_cliente varchar(15)NOT NULL
);

SELECT * FROM CLIENTES